version: 3

silent: true

tasks:
  init:
    desc: Installing package in venv
    cmds:
      - python -m venv .venv
      - .venv/bin/python -m pip install secret-transfer

  clean:
    desc: Cleaning venv
    cmds:
      - rm -rf .venv
