name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-pr-specific-python-version:
    name: Check PR for python ${{ matrix.python_version }}
    runs-on: ubuntu-latest

    permissions:
      contents: read

    strategy:
      matrix:
        python_version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup_environment
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Dependencies
        run: task init

      - name: Lint PR
        run: task lint

      - name: Test Unit
        run: task test-unit

      - name: Test Integration
        run: task test-integration

      - name: Test E2E
        run: task test-e2e

  check-pr:
    runs-on: ubuntu-latest
    if: always() && !cancelled()

    needs:
      - check-pr-specific-python-version

    steps:
      - name: Collect Result
        uses: ovsds/collect-needs-result-action@v1
        with:
          needs_json: ${{ toJson(needs) }}
